### ISSUE TITLE
bug: Missing Window Buttons

### ISSUE THREAD

**Issue by nilswald** [webcatalog/webcatalog-legacy#1453] opened 2021-06-12 08:32 UTC
# Bug Report
**Specifications:**
- WebCatalog Version: Version v33.1.1
- Neutron Version:
- OS (macOS, Windows, Linux): macOS 10.15.7 

**Description:**
No window buttons (traffic light) on new instances. I disabled the window buttons in an existing instance and could not reenable them.

**Steps to Reproduce:**
Create a new instance (with GitHub.com) OR disable window buttons in an existing instance, restart, enable buttons, restart.

**Additional Context**
The new instance was for Github.com, the existing for Asana.

**Comment by quanglam2807** [comment] 2021-06-12 09:27
Thanks for reporting, @nilswald. This would be tricky as I couldn’t reproduce it at all :(

**Comment by nilswald** [comment] 2021-06-12 10:34
try to show and hide the Navigation bar. It seems, that the Window Buttons stick with the Navigation Bar and disappear when it is hidden. I started using the bar just recently when Extension Support was introduced.

**Comment by quanglam2807** [comment] 2021-06-12 15:23
Thank you, @nilswald. It was caused by a bug in Electron. It'll be fixed in the next update: https://github.com/electron/electron/pull/29595

**Closed as completed** 2021-06-22 05:20 UTC
Labels: bug
