### ISSUE TITLE
bug: Some apps turn blank after opening (on M1) 

### ISSUE THREAD

**Issue by jonsnelson** [webcatalog/webcatalog-legacy#1321] opened 2021-01-27 21:40 UTC
# Bug Report
**Specifications:**
- App Version: v28.2.0
- OS (macOS, Windows, Linux): Big Sur on M1 (Mac Mini) 

**Description:**
Some apps open and show the content for a second, and then turn white, ie. content (images/text) all disappear. See picture. 

**Additional Context**

So far, I have noticed this with only two apps: Google Keep and Amazon. (Other apps are fine)
This affects Web Catalogue Engine based apps only. I've deleted, reinstalled these apps, but it hasn't helped. 
<img width="2101" alt="Screen Shot 2021-01-27 at 11 38 52 PM" src="https://user-images.githubusercontent.com/34404707/106057711-0449ca00-60f9-11eb-8891-97d209c63fe1.png">

**Comment by quanglam2807** [comment] 2021-01-28 04:12
I can't reproduce this. @scottrbaxter Can you give it a try, Scott?

**Comment by scottrbaxter** [comment] 2021-01-28 05:41
I attempted to recreate this with the latest WebCatalog `v28.2.0` on macOS `11.1` (M1 Air), using the native Amazon installer and the WebCatalog engine (I generally use [brave.com](https://brave.com) as my default engine). I'm not yet able to reproduce this issue.

When this issue occurs, are you able to consistently reproduce this issue @jonsnelson? For example, can you make this issue occur again after fully quitting the app? After a system reboot?

Also, will the page load correctly with a `cmd-r` refresh?

**Comment by jonsnelson** [comment] 2021-01-28 08:35
Yes- it occurs _every_ time (after fulling quitting app, cmd-r refresh, and a system restart.) 
I have about 30 apps (with the Web Catalogue engine) and only these two have the issue (Keep and Amazon)
Obviously,  I can find a work around (ie. using a different engine) if necessary.

**Comment by scottrbaxter** [comment] 2021-01-28 17:11
Sorry, I'm not able to reproduce the issue on my M1 Air. If this issue is currently limited to a single Mac, then I'd suggest regular end-user troubleshooting steps to see if you can find the culprit. (e.g. clear cookies/caches, try creating a different user on the Mac, create an app, and see if the issue persists, confirm whether/not the issue can be reproduced on another machine, etc.).

There are `Developer Tools` you can toggle on, in the `View` menu. If I were troubleshooting this myself, I'd be digging through that, to see if I could find any errors that help troubleshoot your issue.

**Comment by jonsnelson** [comment] 2021-01-28 20:36
First of all, thanks for the help!
So- I tried all of that and nothing made a difference. Interestingly, however, when I tried opening the Developer Tools I got noticed the page is no longer called by the app's name, rather the generic "Workspace". Also, the tools didn't load since the page was "disconnected". See screenshots:
<img width="1424" alt="Screen Shot 2021-01-28 at 10 28 55 PM" src="https://user-images.githubusercontent.com/34404707/106195675-260a8600-61b9-11eb-84bd-11a5cb2104b5.png">
<img width="2532" alt="Screen Shot 2021-01-28 at 10 29 25 PM" src="https://user-images.githubusercontent.com/34404707/106195726-37539280-61b9-11eb-829f-13a28f4ab6fb.png">

**Comment by scottrbaxter** [comment] 2021-01-29 16:39
That's really interesting. This looks like it may be Electron related? I did a quick search for this error, and found a couple links that may help troubleshoot.

https://stackoverflow.com/questions/55032227/tips-on-solving-devtools-was-disconnected-from-the-page-and-electron-helper-di

https://github.com/electron/electron/issues/21834

https://github.com/electron/electron/issues/19689

Maybe an easy way to fix it would be to delete your current WebCatalog.app, and re-download the latest arm64 version from https://webcatalog.app. I'm not sure if this would necessarily fix the issue, but if the problem is something missing from the app itself, this could potentially resolve it.

Alternatively, @quanglam2807 do you have any suggestions on deleting user level `~/Library` caches/container/application support files/folders that may be causing issues? Obvious folders I see that _should_ be able to be renamed/deleted for a fresh start are `~/Library/Caches/webcatalog/` and `~/Library/Application\ Support/WebCatalog`, though I'd default to the dev on what's best here.

**Comment by quanglam2807** [comment] 2021-01-30 17:57
Thank you so much for the help, @scottrbaxter!

> First of all, thanks for the help!
> So- I tried all of that and nothing made a difference. Interestingly, however, when I tried opening the Developer Tools I got noticed the page is no longer called by the app's name, rather the generic "Workspace". Also, the tools didn't load since the page was "disconnected". See screenshots:
> <img alt="Screen Shot 2021-01-28 at 10 28 55 PM" width="1424" src="https://user-images.githubusercontent.com/34404707/106195675-260a8600-61b9-11eb-84bd-11a5cb2104b5.png">
> <img alt="Screen Shot 2021-01-28 at 10 29 25 PM" width="2000" src="https://user-images.githubusercontent.com/34404707/106195726-37539280-61b9-11eb-829f-13a28f4ab6fb.png">

Thank you for the screenshot. 
- It's perfectly normal that the workspace is called "Workspace 1". By default, the initial workspace of any singlesite app is called "Workspace 1". 
- From the screenshot, I can tell that the page is somewhat loaded (the page title is there). It looks the rendering engine crashes at some point. 

I still don't know what happened exactly. But WebCatalog Engine will receive some underlying changes (mostly in compiling process) soon and it might fix this bug. If not, hopefully, the next version of Electron would resolve this. I understand it's annoying but there's not much I can do now.

**Comment by jonsnelson** [comment] 2021-01-31 21:37
No big deal; as I wrote, I can also use another "engine" for those couple of apps in the meantime. Thanks as always!

**Comment by jonsnelson** [comment] 2021-02-03 06:50
Update after the recent Web Catalogue update (v28.3.0). 
1) The issue seems to be _partially_ resolved for the Amazon app; most internal pages work, but security/account related pages go blank. 
1) Google Keep is still blank.

**Comment by quanglam2807** [comment] 2022-02-03 23:15
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.

**Closed as completed by quanglam2807** 2022-02-03 23:15 UTC
Labels: bug
