### ISSUE TITLE
bug: Unstable hover

### ISSUE THREAD

**Issue by rotu** [webcatalog/webcatalog-legacy#972] opened 2020-08-11 18:37 UTC
# Bug Report
**Specifications:**
- App Version: 9.1.`
- OS (macOS, Windows, Linux): Linux

**Description:**
When I hover the mouse over an interactive element, I expect it to behave one way when the mouse enters and another way when the mouse leaves. It seems like this is not the case - often the hover effect will "strobe" in a visually distracting way.

**Steps to Reproduce:**
1. Install the Dropbox app.
2. Hover your mouse over the "Sign in" button.
3. Observe that the underline that happens when you mouse over sign in flashes irregularly instead of remaining solid.

**Additional Context**
This only seems to happen if the Preferred Browser Engine is Electron.
This seems to happen whether or not hardware acceleration is on.

**Comment by quanglam2807** [comment] 2020-08-13 09:45
Thank you for reporting this. This is probably a Linux bug as I couldn't reproduce it on Mac. I'll try to fix it ASAP.

**Comment by rotu** [comment] 2020-08-13 20:25
I don't see it on Windows either. But comparing it with Windows, one thing I noticed is that the animated SVG arrow also moves smoothly on Windows, whereas the motion stutters on Linux.

**Comment by quanglam2807** [comment] 2022-02-03 05:36
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.

**Closed as completed by quanglam2807** 2022-02-03 05:36 UTC
Labels: bug
