### ISSUE TITLE
feature: allow to add chrome/chromium, firefox and other supported browser extensions

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1265] opened 2020-12-28 20:44 UTC
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

Nowadays life in web browser requires at least some extensions.
E.g.:
* email encryption (#1264 )
* credentials vault (e.g. [Bitwarden](https://bitwarden.com/), [Lastpass](https://www.lastpass.com/), etc.)
* different kind of adblockers
* etc.

When adding new app, then it would be good to allow to add also certain extension to that app.
Also in case of any extension, would be good to set as default to be added to any app, yet still in case of adding any app to be selectable during adding process, whether in current app to add extensions and which ones.

In another words in case of web browser extension:
* configurable, whether to ask to be added or added by default with an option to ask in every case or not
* select all extensions and set these options in bulk

**Additional Context**

Especially hard is to live without credential manager. Currently manually needs to be copied these credentials. Especially boring in case of multisite apps...

**Comment by ScottYates** [comment] 2021-02-21 08:21
I would also like to add my voice to this.  Support for extensions is really the only feature i can think of that is missing!  Please consider this soon!

**Comment by quanglam2807** [comment] 2021-06-05 14:30
Duplicate of https://github.com/webcatalog/webcatalog-app/issues/710. Btw, extension support (very early version) is available in pre-release channel. `WebCatalog > Preferences > Receive pre-release updates`.

**Closed as completed by quanglam2807** 2021-06-05 14:30 UTC
Labels: enhancement
