### ISSUE TITLE
feature: Open Apps in Background at Login

### ISSUE THREAD

**Issue by KibaNoOu** [webcatalog/webcatalog-legacy#1489] opened 2021-08-10 11:59 UTC
# Feature Request
- WebCatalog Version: 36.1.0
- Neutron Version:
- OS (macOS, Windows, Linux): Windows

Right now it's possible to Open the Apps at Lolgin but the apps opens on top and you need to manually minimze them one by one.
So, would be possible to open the app at login but in background in the tray area?

**Comment by quanglam2807** [comment] 2022-02-04 04:20
Thanks for reporting. I'll close this as the problem is probably fixed in the current version. If it's not, please send us a message at https://webcatalog.io/contact/

**Closed as completed by quanglam2807** 2022-02-04 04:20 UTC
Labels: enhancement
