### ISSUE TITLE
bug: ProtonMail is losing login after every restart

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1256] opened 2020-12-28 15:19 UTC
# Bug Report
**Specifications:**
- App Version: 27.4.0
- OS: Linux

[ProtonMail CH](https://app.protonmail.ch/)
WebCatalog Engine: 13.2.0
Electron: 11.1.1
Node: 12.18.3
Chromium: 87.0.4280.88

**Description:**

Every time to start ProtonMail, it requires login.

**Steps to Reproduce:**

* create ProtonMail app via address https://app.protonmail.ch/
* login
* close app
* reopen and again you have to login

**Additional Context**

It is always suggested to use .ch domain due to [that reason](https://protonmail.com/support/knowledge-base/what-is-the-difference-between-protonmail-com-and-protonmail-ch/).

**Comment by edmundlaugasson** [comment] 2021-01-02 13:12
To be honest, it happens with other websites as well. E.g. Google Drive, intranet environments, etc. I've created e.g. multisite app and e.g. Google Drive logs out for longer time, intranet was logged out immediately after closing app. Certainly it needs to be tested more, but so far that's my experience.
E.g. for time to time there are embedded Google Drive documents, that needs to be make easier to change for regular users, to whom the logging in to Google Drive and searching, opening certain document is too complex. Also in such cases it needs to keep certain user logged in to make convenient document changing possible.
Didn't file a new bug as it seems to persist in other sites as well. It will overwhelm you if we file for every site a new bug. I guess there are some common parts, that can be addressed. I know, that every workspace has incognito mode with Chromium (if I'm correct, possibly you are using own custom web browser?), now the question is, how to maintain logged in sessions with such incognito mode over app restarts. For instance, MS Office 365 will keep its login. So, it seems, that it is still possible. In my case, I have MFA, this means I need to enter a code via SMS for time to time in order to authenticate.

**Comment by quanglam2807** [comment] 2022-02-04 03:05
I'll close this issue for now as I couldn't reproduce the problem at all. If it still occurs for you, please email us at https://webcatalog.io/contact/

**Closed as completed by quanglam2807** 2022-02-04 03:05 UTC
Labels: bug
