### ISSUE TITLE
bug: context menu doesn't work In a Pop Up Window.

### ISSUE THREAD

**Issue by jonsnelson** [webcatalog/webcatalog-legacy#797] opened 2020-04-26 12:09 UTC
# Feature Request

In many apps (not all), there is no context menu when you right click on a link (internal/external) from _within_ a pop up window. I don't know if this is a bug, or a feature request.

**Describe Preferred Solution**
A right click context menu with the ability to "Open in New Window" for links within a pop up window. 

**Describe Alternatives**

**Additional Context**

**Comment by linonetwo** [comment] 2020-04-26 13:03
How to get this popup window? What app will pop a window up?

**Comment by quanglam2807** [comment] 2020-04-26 13:23
@linonetwo  you can right click on a click and select Open in new window. I couldn’t reproduce the bug as the context menu in popup window works for me

**Comment by linonetwo** [comment] 2020-04-26 15:21
<img width="883" alt="Screen Shot 2020-04-26 at 11 20 10 PM" src="https://user-images.githubusercontent.com/3746270/80311819-7b71cb00-8814-11ea-8baf-28826f6e2c82.png">


I have full context menu on the opened window, so @jonsnelson may have to give us more details to locate the bug.

**Comment by jonsnelson** [comment] 2020-04-26 19:18
@quanglam2807 So, I get the context menu (and Open Link in New Window) without any issue for some apps, but then in some apps it doesn't happen. (Maybe it is the kind of links they use). 

For example:
In Youtube, I get the right click-context menu in the main parent window, but then in the new pop up window, I cannot right click on any links. 

3 screen shots may help illustrate: 
![capture 1](https://user-images.githubusercontent.com/34404707/80317323-d0f5aa00-880b-11ea-88ac-a37ea361dcce.jpg)
![capture 2](https://user-images.githubusercontent.com/34404707/80317327-d4893100-880b-11ea-9aff-3fe6fe681feb.jpg)
![capture 3](https://user-images.githubusercontent.com/34404707/80317328-d6eb8b00-880b-11ea-9803-79c3959b438a.jpg)

**Comment by quanglam2807** [comment] 2020-04-27 07:59
Resolved by #799.

**Closed as completed by quanglam2807** 2020-04-27 07:59 UTC
Labels: bug
