### ISSUE TITLE
bug: cannot activate with mouse the search field in MS Teams

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1237] opened 2020-12-18 18:05 UTC
# Bug Report
**Specifications:**
- App Version: 27.3.0
- OS: Linux
WebCatalog Engine: 13.0.2
Electron: 11.1.0
Node: 12.18.3
Chromium: 87.0.4280.88

**Description:**

After reopening Teams, cannot activate with mouse the search in MS Teams. Only via CTRL+F.

**Steps to Reproduce:**

1. add MS Teams
2. log in
3. reopen app
4. try to activate with mouse the search field at top center - it is just not possible, only CTRL+F works
To be honest - nothing is possible to choose at the upper bar - also user profile button at right and office apps from left corner.

**Additional Context**

Similar issue might appear also with other apps. It seems that upper edge bar is not possible to click anymore.

**Comment by quanglam2807** [comment] 2020-12-18 18:32
I'm sorry for the bug. I couldn't reproduce the bug with Linux Mint 20. Might I ask which distro are you using?

**Comment by edmundlaugasson** [comment] 2020-12-18 18:37
I am in Linux Mint 20 with Cinnamon. The issue definitely exist - I can share my screen even to show if needed. Recently, few days ago, also clean install done.

**Comment by quanglam2807** [comment] 2020-12-26 13:06
Thank you for reporting. This is probably fixed with https://github.com/webcatalog/webcatalog-engine/pull/247 (WebCatalog Engine 13.2.0). If it's still not fixed, please let me know

**Comment by edmundlaugasson** [comment] 2020-12-26 13:54
Well, updated to WebCatalog 27.4.0 and also apps, currently MS Teams has:
WebCatalog Engine: 13.2.0
Electron: 11.1.1
Node: 12.18.3
Chromium: 87.0.4280.88
Still same issue - with mouse cannot activate search field, only via CTRL+F. Also whole upper edge is not possible to click, e.g. profile button at right corner or choosing apps (9 dot) button at left corner. Luckily only that upper purple bar is not clickable, a bit down all works.

**Comment by quanglam2807** [comment] 2020-12-26 14:28
Temporary fix: Discord > Preferences > Advanced > Use system title bar and borders > Switch on

**Closed as completed** 2020-12-26 16:14 UTC
Labels: bug

**Comment by edmundlaugasson** [comment] 2020-12-26 18:38
Yes, that temporary fix worked :) Although this is still MS Teams :)

**Comment by edmundlaugasson** [comment] 2021-01-04 10:14
I have to report, that this workaround is quite limited. E.g. I can open Settings in Teams but cannot click with mouse nowhere. Only via keyboard is possible to move, select something.
Also experienced, that someone during videoconversation showed something via webcam, but I didn't see anything.

**Comment by quanglam2807** [comment] 2021-01-18 15:31
> I have to report, that this workaround is quite limited. E.g. I can open Settings in Teams but cannot click with mouse nowhere. Only via keyboard is possible to move, select something.
> Also experienced, that someone during videoconversation showed something via webcam, but I didn't see anything.

This is probably fixed in the latest version. It was a bug in Electron.
