### ISSUE TITLE
bug: Dead areas in apps

### ISSUE THREAD

**Issue by lightheaded** [webcatalog/webcatalog-legacy#428] opened 2019-12-01 16:20 UTC
# Bug Report
**Current Behavior:**
In fullscreen (1920x1080) there's an area which captures clicks and prevents from interacting with content underneath it.

**Expected Behavior:**
I need to be able to interact with the container content.

**Steps to Reproduce:**
Open app in fullscreen, try to interact with items on the right. It seems to occur after some time using the app. This occurs in at least Gmail and Google Calendar apps.

**Additional Context**
I'm using MacOS 10.15.1 (19B88) on a 15" MacBook Pro with WebCatalog Version v17.10.0, updated all apps to latest. Using mostly default settings, with Electron as preferred browser engine. Also, here's a video that shows the bug: https://drive.google.com/file/d/1LEhJb_xFZYfVGYBp97CuZBpqZBFpfIGH/view?usp=sharing

**Comment by quanglam2807** [comment] 2019-12-01 16:49
Thanks for reporting, @lightheaded! I'll try to fix it ASAP. Would you mind right-clicking on the dead space and select Inspect Element and see what happens (a screenshot would be great).  At the moment, I'm unable to reproduce the bug on my Macbook.

**Comment by quanglam2807** [comment] 2019-12-01 16:51
Also, based on the UI, it seems like Gmail is not updated. If you can, please open WebCatalog, go to Installed tab and check for updates. That'd be great

**Comment by lightheaded** [comment] 2019-12-01 19:42
I tried to update it and everything seems to be up to date. Interestingly enough, whenever the bug occurs, I am unable to open the developer tools. I'll leave the console open and try to inspect whenever it occurs again. Right clicking the dead area doesn't do anything either..

**Comment by quanglam2807** [comment] 2020-03-28 17:01
This problem has been around for some time and since the app has been upgraded to new version of Electron, I expect this bug to go away. So I'll close this issue for now.  Feel free to let me know if you have any new information.

**Closed as completed by quanglam2807** 2020-03-28 17:01 UTC
Labels: bug
