### ISSUE TITLE
App icon missing issue on Mac

### ISSUE THREAD

**Issue by ChamathJ** [webcatalog/webcatalog-legacy#1185] opened 2020-11-22 06:02 UTC
Some app icons are missing on Launchpad and Dock on Mac. electron.icns file is damaged on those apps.

![Screenshot 2020-11-22 at 11 28 04@2x](https://user-images.githubusercontent.com/37962078/99896354-ee152d00-2cb5-11eb-9610-de79531a9c2d.png)
<img width="372" alt="Screenshot 2020-11-22 at 11 30 43@2x" src="https://user-images.githubusercontent.com/37962078/99896406-451b0200-2cb6-11eb-9dde-731f55eef029.png">

**Comment by quanglam2807** [comment] 2020-11-23 03:13
@ChamathJ Did you create apps with custom PNG files? Or does it happen with apps in the catalog as well?

**Comment by ChamathJ** [comment] 2020-11-23 07:16
It happens with both custom apps and apps in the catalog. (Mostly catalog apps)

**Comment by quanglam2807** [comment] 2020-11-23 07:20
@ChamathJ Is it possible for you to share the names of the apps explicitly? It would help a lot. 

I'm not able to reproduce this on my Mac so it'd take some time to figure out what happened exactly.

**Comment by ChamathJ** [comment] 2020-11-23 08:07
@quanglam2807 I thought that this is a known issue. It happened to almost all apps within this year. OneDrive, Outlook app icons were missing on one day, so I had to reinstall them. Gmail, Amazon icons were missing a few days later. Likewise, this happens to every app randomly. I experienced this for more than 20 catalog & custom apps.

**Comment by quanglam2807** [comment] 2020-11-23 08:54
Hmm, strange. Does it happen after you update the apps? Or does it just happen randomly?

If possible, can you zip on the corrupted apps and share the file with me?

**Comment by ChamathJ** [comment] 2020-11-23 10:55
@quanglam2807 I think it's happening after updating apps. It just happened for two apps after updating them today.

Corrupted apps:
https://we.tl/t-mKgjehzWKn

**Comment by quanglam2807** [comment] 2020-11-23 13:01
Thank you, @ChamathJ. I guess you have quite a lot of apps? I have a fix in place. Hopefully, it'll resolve this.

**Comment by quanglam2807** [comment] 2020-11-23 16:18
The fix is up with v26.3.0. Please give it a try :)

**Comment by ChamathJ** [comment] 2020-11-23 17:40
@quanglam2807 That update restored the icons of previously corrupted apps, but also corrupted another two apps. :(

**Comment by quanglam2807** [comment] 2020-11-23 17:41
I

**Comment by quanglam2807** [comment] 2020-11-23 17:43
Then the bug must be related to something else. How many apps do you have in total @ChamathJ? I’m guessing the bug might happen if there’re a large number of apps.

**Comment by ChamathJ** [comment] 2020-11-23 17:45
@quanglam2807 20 apps at the moment.

**Comment by quanglam2807** [comment] 2020-11-23 17:47
It'll take some time for me to figure out what happens. This bug is so random.

**Comment by ChamathJ** [comment] 2020-11-23 17:51
@quanglam2807 Okay. Thank you.

**Comment by quanglam2807** [comment] 2020-11-23 18:07
@ChamathJ Btw, which macOS version are you running?

**Comment by ChamathJ** [comment] 2020-11-23 18:13
@quanglam2807 Currently I’m using Big Sur and it happened on Catalina as well.

**Comment by quanglam2807** [comment] 2020-11-23 18:16
Thank you, @ChamathJ 

It looks like a bug with `electron-packager`: https://github.com/electron/electron-packager/issues/691

**Comment by quanglam2807** [comment] 2020-11-23 19:43
@ChamathJ Can you give v26.4.0 https://github.com/webcatalog/webcatalog-app/releases/tag/v26.4.0 a try? I probably won't fix the bug but it allows me to collect some insights for debugging.

**Comment by ChamathJ** [comment] 2020-11-24 13:07
@quanglam2807 Okay

**Comment by quanglam2807** [comment] 2020-11-30 17:24
Does the bug still occur on v26.5.0?

**Comment by ChamathJ** [comment] 2020-12-01 01:26
@quanglam2807 Seems like no issue after the update. :) I'll let you know if something happens.

**Comment by quanglam2807** [comment] 2020-12-02 04:47
The bug is completely fixed in v26.6.1 :)

**Comment by ChamathJ** [comment] 2020-12-04 04:24
@quanglam2807 After updating apps today, three app icons were corrupted (including FB). 

https://we.tl/t-IEofEphN6u

**Comment by quanglam2807** [comment] 2020-12-04 04:25
Can you check which version of WebCatalog are you running?

**Comment by ChamathJ** [comment] 2020-12-04 04:27
@quanglam2807 v26.6.1

**Comment by quanglam2807** [comment] 2020-12-04 04:29
Thank you. I'll have a look shortly.

**Closed as completed** 2020-12-04 16:08 UTC
Labels: bug

**Comment by quanglam2807** [comment] 2020-12-08 17:38
Please give v27.0.0-alpha a try. It's supposed to fix the bug, but if it doesn't please let me know. Also, I've add an option to reinstall (repair) an app in case it is corrupted.

https://github.com/webcatalog/webcatalog-app/releases/tag/v27.0.0-alpha

**Comment by ChamathJ** [comment] 2020-12-09 09:16
@quanglam2807 I'll try and let you know.
